package frc.robot.subsystems.leds;

import edu.wpi.first.wpilibj.util.Color;

public class RobocketsColorPalette {
    // Here's a bullshit list of colors that we can use for the LEDs
    public static final StupidColor[] LEDColorList = {
        new StupidColor(Color.kDenim),
        new StupidColor(Color.kFirstBlue),
        new StupidColor(Color.kFirstRed),
        new StupidColor(Color.kAliceBlue),
        new StupidColor(Color.kAqua),
        new StupidColor(Color.kAquamarine),
        new StupidColor(Color.kBeige),
        new StupidColor(Color.kBisque),
        new StupidColor(Color.kBlack),
        new StupidColor(Color.kBlanchedAlmond),
        new StupidColor(Color.kBlue),
        new StupidColor(Color.kBlueViolet),
        new StupidColor(Color.kBrown),
        new StupidColor(Color.kBurlywood),
        new StupidColor(Color.kCadetBlue),
        new StupidColor(Color.kChartreuse),
        new StupidColor(Color.kChocolate),
        new StupidColor(Color.kCoral),
        new StupidColor(Color.kCornflowerBlue),
        new StupidColor(Color.kCornsilk),
        new StupidColor(Color.kCrimson),
        new StupidColor(Color.kCyan),
        new StupidColor(Color.kDarkBlue),
        new StupidColor(Color.kDarkCyan),
        new StupidColor(Color.kDarkGoldenrod),
        new StupidColor(Color.kDarkGreen),
        new StupidColor(Color.kDarkKhaki),
        new StupidColor(Color.kDarkMagenta),
        new StupidColor(Color.kDarkOliveGreen),
        new StupidColor(Color.kDarkOrange),
        new StupidColor(Color.kDarkOrchid),
        new StupidColor(Color.kDarkRed),
        new StupidColor(Color.kDarkSalmon),
        new StupidColor(Color.kDarkSeaGreen),
        new StupidColor(Color.kDarkSlateBlue),
        new StupidColor(Color.kDarkTurquoise),
        new StupidColor(Color.kDarkViolet),
        new StupidColor(Color.kDeepPink),
        new StupidColor(Color.kDeepSkyBlue),

        //0x696969
        new StupidColor(Color.kDimGray),

        new StupidColor(Color.kDodgerBlue),
        new StupidColor(Color.kFirebrick),
        new StupidColor(Color.kForestGreen),
        new StupidColor(Color.kFuchsia),
        new StupidColor(Color.kGold),
        new StupidColor(Color.kGoldenrod),
        new StupidColor(Color.kGray),
        new StupidColor(Color.kGreen),
        new StupidColor(Color.kGreenYellow),
        new StupidColor(Color.kHotPink),
        new StupidColor(Color.kIndianRed),
        new StupidColor(Color.kIndigo),
        new StupidColor(Color.kKhaki),
        new StupidColor(Color.kLavender),
        new StupidColor(Color.kLavenderBlush),
        new StupidColor(Color.kLawnGreen),
        new StupidColor(Color.kLightBlue),
        new StupidColor(Color.kLightCoral),
        new StupidColor(Color.kLightGreen),
        new StupidColor(Color.kLightPink),
        new StupidColor(Color.kLightSalmon),
        new StupidColor(Color.kLightSeaGreen),
        new StupidColor(Color.kLightSkyBlue),
        new StupidColor(Color.kLightSteelBlue),
        new StupidColor(Color.kLime),
        new StupidColor(Color.kLimeGreen),
        new StupidColor(Color.kMagenta),
        new StupidColor(Color.kMaroon),
        new StupidColor(Color.kMediumAquamarine),
        new StupidColor(Color.kMediumBlue),
        new StupidColor(Color.kMediumOrchid),
        new StupidColor(Color.kMediumPurple),
        new StupidColor(Color.kMediumSeaGreen),
        new StupidColor(Color.kMediumSlateBlue),
        new StupidColor(Color.kMediumSpringGreen),
        new StupidColor(Color.kMediumTurquoise),
        new StupidColor(Color.kMediumVioletRed),
        new StupidColor(Color.kMidnightBlue),
        new StupidColor(Color.kMistyRose),
        new StupidColor(Color.kMoccasin),
        new StupidColor(Color.kNavajoWhite),
        new StupidColor(Color.kNavy),
        new StupidColor(Color.kOliveDrab),
        new StupidColor(Color.kOrange),
        new StupidColor(Color.kOrangeRed),
        new StupidColor(Color.kOrchid),
        new StupidColor(Color.kPaleGoldenrod),
        new StupidColor(Color.kPaleGreen),
        new StupidColor(Color.kPaleTurquoise),
        new StupidColor(Color.kPaleVioletRed),
        new StupidColor(Color.kPapayaWhip),
        new StupidColor(Color.kPeachPuff),
        new StupidColor(Color.kPeru),
        new StupidColor(Color.kPink),
        new StupidColor(Color.kPlum),
        new StupidColor(Color.kPowderBlue),
        new StupidColor(Color.kPurple),
        new StupidColor(Color.kRed),
        new StupidColor(Color.kRosyBrown),
        new StupidColor(Color.kRoyalBlue),
        new StupidColor(Color.kSaddleBrown),
        new StupidColor(Color.kSalmon),
        new StupidColor(Color.kSandyBrown),
        new StupidColor(Color.kSeaGreen),
        new StupidColor(Color.kSienna),
        new StupidColor(Color.kSkyBlue),
        new StupidColor(Color.kSlateBlue),
        new StupidColor(Color.kSpringGreen),
        new StupidColor(Color.kSteelBlue),
        new StupidColor(Color.kTan),
        new StupidColor(Color.kTeal),
        new StupidColor(Color.kTomato),
        new StupidColor(Color.kTurquoise),
        new StupidColor(Color.kViolet),
        new StupidColor(Color.kWheat),
        new StupidColor(Color.kWhite),
        new StupidColor(Color.kYellow),
        new StupidColor(Color.kYellowGreen)
    };

    public static StupidColor getRandomColor() {
        return LEDColorList[(int)(Math.random()*LEDColorList.length)];
    }
}
